version: '3'
services:
  seed:
    image: akka_chat
    stdin_open: true
    ports:
      - '1600:1600'
    environment:
      NODE_NAME: seed
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
  node:
    image: akka_chat
    stdin_open: true
    environment:
      CLUSTER_IP: ""
      CLUSTER_PORT: 0
      SEED_PORT_1600_TCP_ADDR: seed
